# Generated by Django 3.0.2 on 2020-02-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energized-id', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WelcomMessage',
            new_name='WelcomeMessage',
        ),
    ]
