# Generated by Django 3.0.2 on 2020-02-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0002_auto_20200212_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=200)),
                ('alert_color', models.CharField(choices=[('success', 'green'), ('primary', 'blue'), ('warning', 'yellow'), ('danger', 'red')], max_length=200)),
                ('alert_content', models.TextField()),
                ('alert_dismissable', models.BooleanField()),
                ('alert_expires', models.BooleanField()),
                ('alert_expiresDate', models.DateTimeField(verbose_name='Date Alert Expires (Leave blank if no expiration)')),
            ],
        ),
    ]
