# Generated by Django 3.0.3 on 2020-03-16 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0005_auto_20200316_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertmessage',
            old_name='alert_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='alertmessage',
            old_name='alert_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='alertmessage',
            old_name='alert_dismissable',
            new_name='dismissable',
        ),
        migrations.RenameField(
            model_name='alertmessage',
            old_name='alert_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='badgepage',
            old_name='badge_content',
            new_name='badge',
        ),
        migrations.RenameField(
            model_name='badgepage',
            old_name='badge_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='badgepage',
            old_name='badge_published',
            new_name='published',
        ),
        migrations.AddField(
            model_name='badgepage',
            name='slug',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
