# Generated by Django 3.0.3 on 2020-03-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0006_auto_20200316_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.TextField()),
                ('badge', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BadgePage',
        ),
    ]
