# Generated by Django 3.0.3 on 2020-03-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0007_auto_20200317_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetemplate',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='slug',
            field=models.TextField(max_length=50),
        ),
    ]
