# Generated by Django 3.0.3 on 2020-03-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0012_auto_20200317_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetemplate',
            name='badge',
            field=models.BinaryField(editable=True),
        ),
    ]
