# Generated by Django 3.0.3 on 2020-03-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0014_auto_20200317_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgetemplate',
            old_name='badge',
            new_name='template',
        ),
    ]
