# Generated by Django 3.0.3 on 2020-03-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0017_auto_20200318_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetemplate',
            name='template',
            field=models.FileField(unique=True, upload_to='badgeTemplates/'),
        ),
    ]
