# Generated by Django 3.0.5 on 2020-05-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0018_auto_20200318_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetemplate',
            name='config',
            field=models.FileField(default=None, unique=True, upload_to='badgeTemplates/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
