# Generated by Django 3.0.5 on 2020-05-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0019_auto_20200506_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgetemplate',
            old_name='config',
            new_name='configFile',
        ),
    ]
