# Generated by Django 3.0.8 on 2020-12-13 05:43

import LibreBadge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreBadge', '0020_auto_20200506_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetemplate',
            name='configFile',
            field=models.FileField(unique=True, upload_to=LibreBadge.models.BadgeTemplate.upload_file_name),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='template',
            field=models.FileField(unique=True, upload_to=LibreBadge.models.BadgeTemplate.upload_file_name),
        ),
    ]
